### ISSUE TITLE
后台抛错

### ISSUE THREAD

**Issue by firefairy198** [HatoYuze/life-restart-bot#2]
2024-12-11 01:59:25 V/Bot.2664869475: [极]梦幻泡影(335693890) -> /remake start
2024-12-11 01:59:26 V/Bot.2664869475: Friend(335693890) <- 请在抽取的随机天赋中共选择3个：
 >直接输入对应的序号即可，数字间由英文逗号相隔(如: 1,2,3)
1：不离不弃
   你不会离婚
2：半神
   所有属性+2
3：阴间大会员
   随机属性+8
4：早产儿
   所有属性-1
5：把握不住
   你有强迫症
6：返老还童
   可能会回到年轻的时候
7：潜能
   家境<0时其他属性+1
8：神秘的小盒子
   100岁时才能开启
9：橙色转盘
   变成随机橙色天赋
10：海的女儿
   颜值-2，初始可用属性点+1
[mirai:quote:[mirai:source:ids=[20875], internalIds=[1102565971], from friend 335693890 to 2664869475 at 1733853565], content=/remake start]
2024-12-11 01:59:36 W/LifeRestarter: Exception in executing command `[mirai:source:ids=[20875], internalIds=[1102565971], from friend 335693890 to 2664869475 at 1733853565]/remake start`
 command owned by LifeRestarter v0.1.1 with Friend(335693890)
java.lang.NullPointerException
        at life-restart-bot-0.2.2.mirai2.jar//com.github.hatoyuze.restarter.game.entity.Life.finishUserEvent(Life.kt:54)
        at life-restart-bot-0.2.2.mirai2.jar//com.github.hatoyuze.restarter.game.entity.Life.nextEvents(Life.kt:42)
        at life-restart-bot-0.2.2.mirai2.jar//com.github.hatoyuze.restarter.game.entity.Life.next(Life.kt:124)
        at life-restart-bot-0.2.2.mirai2.jar//com.github.hatoyuze.restarter.game.LifeEngine$iterator$1.next(LifeEngine.kt:65)
        at life-restart-bot-0.2.2.mirai2.jar//com.github.hatoyuze.restarter.game.LifeEngine$iterator$1.next(LifeEngine.kt:59)
        at kotlin.sequences.SequencesKt___SequencesKt.toCollection(_Sequences.kt:787)
        at kotlin.sequences.SequencesKt___SequencesKt.toMutableList(_Sequences.kt:817)
        at kotlin.sequences.SequencesKt___SequencesKt.toList(_Sequences.kt:808)
        at life-restart-bot-0.2.2.mirai2.jar//com.github.hatoyuze.restarter.mirai.RestartLifeCommand.start(RestartLifeCommand.kt:66)
        at life-restart-bot-0.2.2.mirai2.jar//com.github.hatoyuze.restarter.mirai.RestartLifeCommand$start$1.invokeSuspend(RestartLifeCommand.kt)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:33)
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

2024-12-11 01:59:36 V/Bot.2664869475: [极]梦幻泡影(335693890) -> 8,9,3

**Comment by HatoYuze** [comment]
这貌似是因为修仙事件不完善导致的
我看看有没有办法解决
